#!/bin/bash
# ================================================================
# generate-secrets.sh
# ================================================================
# Reads TLS certs from ./certs/ and writes a complete 01-secrets.yaml
# with real base64-encoded certificate values.
#
# Usage:   cd TLSOC-K3s && bash generate-secrets.sh
# Output:  k8s/01-secrets.yaml (overwritten with real cert data)
# ================================================================

set -e

CERTS_DIR="./certs"
OUTPUT="./k8s/01-secrets.yaml"

echo "═══════════════════════════════════════════════════"
echo "  TLSOC — Generating Kubernetes Secrets"
echo "═══════════════════════════════════════════════════"

# Check that certs exist
for f in ca/ca.crt elasticsearch/elasticsearch.crt elasticsearch/elasticsearch.key \
         kibana/kibana.crt kibana/kibana.key logstash/logstash.crt logstash/logstash.key; do
  if [ ! -f "$CERTS_DIR/$f" ]; then
    echo "❌ ERROR: Missing cert file: $CERTS_DIR/$f"
    echo "   Make sure the certs/ folder has all TLS certificates."
    exit 1
  fi
done

echo "📂 Reading certificates from: $CERTS_DIR"

# Base64 encode all cert files (no line wrapping)
CA_CRT=$(base64 -w 0 < "$CERTS_DIR/ca/ca.crt")
ES_CRT=$(base64 -w 0 < "$CERTS_DIR/elasticsearch/elasticsearch.crt")
ES_KEY=$(base64 -w 0 < "$CERTS_DIR/elasticsearch/elasticsearch.key")
KB_CRT=$(base64 -w 0 < "$CERTS_DIR/kibana/kibana.crt")
KB_KEY=$(base64 -w 0 < "$CERTS_DIR/kibana/kibana.key")
LS_CRT=$(base64 -w 0 < "$CERTS_DIR/logstash/logstash.crt")
LS_KEY=$(base64 -w 0 < "$CERTS_DIR/logstash/logstash.key")

cat > "$OUTPUT" << EOF
# ⚠️  AUTO-GENERATED by generate-secrets.sh — DO NOT COMMIT TO GIT
# Contains real TLS certificate data. Re-run generate-secrets.sh to update.

apiVersion: v1
kind: Secret
metadata:
  name: tlsoc-credentials
  namespace: tlsoc
type: Opaque
stringData:
  ELASTIC_PASSWORD: "DTJvrIiQdd6C5D1dKO=-"
  KIBANA_PASSWORD: "RT+_iIQt8zPJOtBRE5mw"
  MAXMIND_LICENSE_KEY: "YOUR_MAXMIND_KEY_HERE"
  XPACK_ENCRYPTION_KEY: "9f3a8c1e5d7b4a2f6c9d8e7a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8"

---
apiVersion: v1
kind: Secret
metadata:
  name: tlsoc-credentials
  namespace: tlsoc-ops
type: Opaque
stringData:
  ELASTIC_PASSWORD: "DTJvrIiQdd6C5D1dKO=-"
  KIBANA_PASSWORD: "RT+_iIQt8zPJOtBRE5mw"

---
apiVersion: v1
kind: Secret
metadata:
  name: tlsoc-tls-certs
  namespace: tlsoc
type: Opaque
data:
  ca.crt: $CA_CRT
  elasticsearch.crt: $ES_CRT
  elasticsearch.key: $ES_KEY
  kibana.crt: $KB_CRT
  kibana.key: $KB_KEY
  logstash.crt: $LS_CRT
  logstash.key: $LS_KEY

---
apiVersion: v1
kind: Secret
metadata:
  name: tlsoc-tls-certs
  namespace: tlsoc-ops
type: Opaque
data:
  ca.crt: $CA_CRT
EOF

echo "✅ Generated: $OUTPUT"
echo "   All 7 certificate files embedded successfully."
echo ""
echo "Next: run 'bash deploy.sh' to deploy the full stack."
