apiVersion: apps/v1
kind: Deployment
metadata:
  name: foss-engine
  namespace: tlsoc
spec:
  replicas: {{ .Values.foss_engine.replicas }}
  selector:
    matchLabels:
      app: foss-engine
  template:
    metadata:
      labels:
        app: foss-engine
    spec:
      terminationGracePeriodSeconds: 45
      containers:
        - name: foss-engine
          image: foss-soc-engine:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.foss_engine.resources.requests.cpu | quote }}
              memory: {{ .Values.foss_engine.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.foss_engine.resources.limits.cpu | quote }}
              memory: {{ .Values.foss_engine.resources.limits.memory | quote }}
          env:
            - name: REDIS_HOST
              value: "redis.tlsoc.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: parser-output
              mountPath: /var/log/soc_output
            - name: engine-logs
              mountPath: /app/logs
            - name: engine-config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: parser-output
          persistentVolumeClaim:
            claimName: parser-output
        - name: engine-logs
          persistentVolumeClaim:
            claimName: foss-engine-logs
        - name: engine-config
          configMap:
            name: engine-config
