apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-files
  namespace: tlsoc
data:
  dashboards.ndjson: |-
{{ .Files.Get "files/dashboards.ndjson" | indent 4 }}
  rules.ndjson: |-
{{ .Files.Get "files/rules.ndjson" | indent 4 }}
binaryData:
  logo.png: {{ .Files.Get "files/logo.png" | b64enc | quote }}
