apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: elasticsearch-vpa
  namespace: tlsoc
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: tlsoc-es-default
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kafka-vpa
  namespace: tlsoc
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: kafka
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kibana-vpa
  namespace: tlsoc
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tlsoc-kb
  updatePolicy:
    updateMode: "Off"
---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: foss-engine-vpa
  namespace: tlsoc
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: foss-engine
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis-vpa
  namespace: tlsoc
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: redis
  updatePolicy:
    updateMode: "Off"
